FIX A100 Slurm problems

diff --git a/Slurm_A100/climax_frozen b/Slurm_A100/climax_frozen
--- a/Slurm_A100/climax_frozen
+++ b/Slurm_A100/climax_frozen
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-#SBATCH --job-name="SC6-basetest-climax"
+#SBATCH --job-name="SC6-A100-basetest-climax_frozen"
 
 #SBATCH --nodes=1
 
-#SBATCH --gpus-per-node=rtx8000:1 # specify gpu
+#SBATCH --gpus-per-node=a100:1 --constraint="dgx&ampere"       # specify gpu
 
 #SBATCH --ntasks-per-node=1
 
@@ -14,7 +14,7 @@
 
 #SBATCH --time=48:00:00                                  # set runtime
 
-#SBATCH -o /home/mila/f/felix-andreas.nahrstedt/Slurm/SC6-basetest-climax.out        # set log dir to home
+#SBATCH -o /home/mila/f/felix-andreas.nahrstedt/Slurm/SC6-A100-basetest-climax_frozen.out        # set log dir to home
 
 
 EXP_NAME=$1
@@ -49,7 +49,7 @@ else
     python -m venv env_old_emulator
     source env_old_emulator/bin/activate
     #bash download_climateset.sh || { echo "Failed to run download_climateset.sh"; exit 1; }
-    bash download_climax_checkpoints.sh || { echo "Failed to run download_climax_checkpoints.sh"; exit 1; }
+    #bash download_climax_frozen_checkpoints.sh || { echo "Failed to run download_climax_frozen_checkpoints.sh"; exit 1; }
     pip install -r requirements.txt || { echo "Failed to install requirements."; exit 1; }
     pip install pytorch-lightning==1.8.3  || { echo "Failed to install pytorch-lightning old version"; exit 1; }
 fi
@@ -65,11 +65,11 @@ export NCCL_BLOCKING_WAIT=1 #Pytorch Lightning uses the NCCL backend for inter-G
 # 8. Run Python
 export HYDRA_FULL_ERROR=1
 echo "Running python test.py ..."
-srun  python emulator/run.py experiment=superemulator/superemulator_climax_tas+pr_run-02.yaml seed=3423
+srun  python emulator/run.py experiment=superemulator/superemulator_climax_frozen_tas+pr_run-02.yaml seed=3423
 
 
 # 9. Copy output to scratch
-#cp /home/mila/f/felix-andreas.nahrstedt/Slurm/SC6-basetest-climax_out.out 
+#cp /home/mila/f/felix-andreas.nahrstedt/Slurm/SC6-A100-basetest-climax_frozen_out.out 
 
 # 10. Experiment is finished
 
